name: Build and Publish

on: [push, pull_request]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.16.2
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm run build
    - if: github.ref == 'refs/heads/master'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - if: github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v1
      with:
        path: ./*.tgz
